services:    
  app-dev:
    build: ./
    container_name: app-dev
    restart: unless-stopped
    hostname: app-dev
    ports:
      - 8000:8000
    networks:
      - app-net
    env_file:
      - .env

  app-stg:
    build: ./
    container_name: app-stg
    restart: unless-stopped
    hostname: app-stg
    ports:
      - 8000:8000
    networks:
      - app-net
    env_file:
      - .env

  app-prd:
    image: ${APP_IMAGE}:${APP_TAG}
    container_name: app-prd
    restart: unless-stopped
    hostname: app-prd
    ports:
      - 8000:8000
    networks:
      - app-net
    env_file:
      - .env

networks:
  app-net:
    driver: bridge
