# Workflow ini akan melakukan build dan testing terhadap development app.
name: Development Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-testing:
    name: Build and Testing 🔎 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> .env
          echo "MLFLOW_DEPLOY_MODEL_ALIAS=${{ vars.MLFLOW_DEPLOY_MODEL_DEV }}" >> .env
          echo "APP_ENDPOINT=${{ vars.APP_ENDPOINT_DEV }}" >> .env

      - name: Build and Run Container
        run: |
          sudo docker compose up app-dev --build --detach
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Hit Endpoint
        run: |
          sleep 20
          curl http://localhost:8000/
          
      - name: Testing
        run: |
          export $(grep -v '^#' .env | xargs)
          python3 test.py